version: '3.10'

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5500:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 2461
      POSTGRES_DB: flask_crud